steps:
  - name: maven:3-openjdk-8
    id: "mvn-test"
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-openjdk-8
    id: "mvn-package"
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "gcr.io/achilio-dev/mvm-service",
        "--build-arg=JAR_FILE=target/alwaysmart-optimizer-0.0.1-SNAPSHOT.jar",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/achilio-dev/mvm-service"]
  - name: maven:3-openjdk-8
    entrypoint: "mvn"
    args: ["package", "appengine:deploy"]
images: ["gcr.io/achilio-dev/mvm-service"]
# - name: 'gcr.io/cloud-builders/curl'
#   id: 'codecov-report'
#   waitFor: ['mvn-test']
#   entrypoint: bash
#   args: ['-c', 'bash <(curl -s https://codecov.io/bash)']
#   env:
#   - 'VCS_COMMIT_ID=$COMMIT_SHA'
#   - 'VCS_BRANCH_NAME=$BRANCH_NAME'
#   - 'VCS_PULL_REQUEST=$_PR_NUMBER'
#   - 'CI_BUILD_ID=$BUILD_ID'
#   - 'CODECOV_TOKEN=7eba3863-665f-4a7b-ae66-478ef51cb7fa' # _CODECOV_TOKEN is user user substituion variable specified in my cloud build trigger
