steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['test']
steps:
- name: maven:3-jdk-8
  entrypoint: mvn
  args: ['package','-Dmaven.test.skip=true']
# steps:
# - name: gcr.io/cloud-builders/docker
#   args: ['build', '-t', 'gcr.io/goptimal/optimizer', '--build-arg=JAR_FILE=target/alwaysmart-optimizer-0.0.1-SNAPSHOT.jar', '.']
# images: ['gcr.io/goptimal/optimizer']
