---
coverage:
  range: "40...90"
  ignore:
    - "src/main/java/com/achilio/mvm/service/MVGeneratorApplication.java"
    - "src/main/java/com/achilio/mvm/service/ServletInitializer.java"
    - "src/main/java/com/achilio/mvm/service/exceptions/**/*"
    - "src/main/java/com/achilio/mvm/service/GooglePubSubService.java"