---
coverage:
  range: "40...100"
  ignore:
    - "src/main/java/com/achilio/mvm/service/OptimizerApplication.java"
    - "src/main/java/com/achilio/mvm/service/ServletInitializer.java"
    - "src/main/java/com/achilio/mvm/service/exceptions/*"