# Use postgres/example user/password credentials
version: "3.1"

services:
  web:
    image: mvm-service
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/optimizer_dev
      SPRING_DATASOURCE_USERNAME: optimizer
      SPRING_DATASOURCE_PASSWORD: optimizer
      GOOGLE_CLOUD_PROJECT: achilio-dev

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: optimizer
      POSTGRES_PASSWORD: optimizer
      POSTGRES_DB: optimizer_dev

  adminer:
    image: adminer
    ports:
      - 8088:8080
